### ISSUE TITLE
Uncaught TypeError: Cannot read property 'body' of null

### ISSUE THREAD

**Issue by yaronuliel** [cdnjs/atom-extension#19]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: [cdnjs-atom-extension](https://github.com/cdnjs/atom-extension) package, v1.5.2

### Stack Trace

Uncaught TypeError: Cannot read property 'body' of null

```
At /Users/techmarketing/.atom/packages/cdnjs/lib/cdnjs-view.coffee:49

TypeError: Cannot read property 'body' of null
  at /Users/techmarketing/.atom/packages/cdnjs/lib/cdnjs-view.coffee:47:8
  at Request.callback (/Users/techmarketing/.atom/packages/cdnjs/node_modules/superagent/lib/node/index.js:785:12)
  at Stream.<anonymous> (/Users/techmarketing/.atom/packages/cdnjs/node_modules/superagent/lib/node/index.js:990:12)
  at emitNone (events.js:72:20)
  at Stream.emit (events.js:166:7)
  at Unzip.<anonymous> (/Users/techmarketing/.atom/packages/cdnjs/node_modules/superagent/lib/node/utils.js:108:12)
  at emitNone (events.js:72:20)
  at Unzip.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```

### Commands

```
     -3:56 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:55.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:55.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:55.3.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:51.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:51.9.0 settings-view:view-installed-packages (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:44 core:backspace (atom-text-editor.editor.is-focused)
     -2:42.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:28.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:01.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:55.7.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.mini.is-focused)
     -0:52.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:49.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:49.5.0 settings-view:view-installed-packages (atom-text-editor.editor)
     -0:23.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:23 core:copy (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
cdnjs, v1.5.0
emmet, v2.3.13
linter, v1.10.0
linter-jscs, v3.2.0
linter-jshint, v1.2.1
svn, v0.0.8

# Dev
No dev packages
```

**Comment by thomasdavis** [comment]
Thanks for the excellent pull request and sorry for never getting back to you.

This most likely happened due to the API server being down at the time.

I will have to wrap the network requests such that they fail more gracefully.
