### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by jsbalrog** [cdnjs/atom-extension#2]
When I right-click in source tree, then select Download file from cdnjs, I get "Uncaught TypeError: Cannot read property 'getPath' of undefined" error.

**Comment by julianorafael** [comment]
I'm having the same problem here

**Comment by nahkar** [comment]
I'm having the same problem here

**Comment by ksprwhite** [comment]
what is your atom version and OS ? please paste error stack trace here.

**Comment by faouzzz** [comment]
same here.

[Enter steps to reproduce below:]

1. Right click on editor body
2. Click on "Download file from cdnjs"

**Atom Version**: 1.0.19
**System**: Windows 10
**Thrown From**: [cdnjs](https://github.com/cdnjs/atom-extension) package, v1.5.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /C:/Users/username/.atom/packages/cdnjs/lib/cdnjs-view.coffee:97

TypeError: Cannot read property 'getPath' of undefined
  at CdnjsView.module.exports.CdnjsView.toggle (C:\Users\username\.atom\packages\cdnjs\lib\cdnjs-view.coffee:75:36)
  at Object.module.exports.DownloadFile (C:\Users\username\.atom\packages\cdnjs\lib\cdnjs.coffee:29:16)
  at atom-workspace.atom.commands.add.cdnjs:DownloadFile (C:\Users\username\.atom\packages\cdnjs\lib\cdnjs.coffee:12:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:157:33)
  at HTMLDocument.handler (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -6:17.7.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -6:12.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:12.5.0 copy-config-info:copy (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -5:34.1.0 core:cancel (atom-pane.pane.active)
     -5:32.9.0 settings-view:open (atom-pane.pane.active)
     -1:25.8.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -1:21.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-minify, v0.4.2
autocomplete-paths, v1.0.2
cakephp3-snippets, v0.5.0
cdnjs, v1.5.0
color-picker, v2.0.12
emmet, v2.3.13
fetch, v0.3.0
language-ini, v1.12.0
language-powershell, v2.1.0
linter, v1.6.0
linter-clang, v3.2.2
linter-coffeelint, v1.1.0
linter-gcc, v0.3.8
linter-js-standard, v3.2.0
linter-jsonlint, v1.0.1
linter-less, v2.1.0
linter-lua, v1.0.0
linter-php, v1.0.4
linter-pylint, v1.0.0
linter-ruby, v1.1.1
linter-sass-lint, v0.1.5
linter-tidy, v1.0.1
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-selection, v4.3.0
open-recent, v2.3.0
php-composer-completion, v0.3.4
php-debug, v0.1.3
pigments, v0.15.0

# Dev
No dev packages
```

**Comment by ksprwhite** [comment]
@faouzzz this was fixed from v1.5.1.

Try uninstall and install "cdnjs-atom-extension" package, please see f0b86e92e7218389815503179f0f75f45a690bf5

**Comment by faouzzz** [comment]
Thank you, that work now.

I have another error when i try on a empty tab. see below.
Putting the content of the downloaded file would be great in this case ?

[Enter steps to reproduce below:]

1. on a untitled tab (no file)
2. right click on body (atom-text-editor ?)
3. click on "Download file from cdnjs"

**Atom Version**: 1.0.19
**System**: Windows 10
**Thrown From**: [cdnjs-atom-extension](https://github.com/cdnjs/atom-extension) package, v1.5.2


### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /C:/Users/username/.atom/packages/cdnjs-atom-extension/lib/cdnjs-view.coffee:100

TypeError: Cannot read property 'file' of undefined
  at CdnjsView.module.exports.CdnjsView.toggle (C:\Users\username\.atom\packages\cdnjs-atom-extension\lib\cdnjs-view.coffee:76:34)
  at Object.module.exports.DownloadFile (C:\Users\username\.atom\packages\cdnjs-atom-extension\lib\cdnjs.coffee:32:16)
  at atom-workspace.subscriptions.add.atom.commands.add.cdnjs:DownloadFile (C:\Users\username\.atom\packages\cdnjs-atom-extension\lib\cdnjs.coffee:15:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\atom.asar\renderer\api\lib\remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:157:33)
  at HTMLDocument.handler (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\username\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
 17x -0:56.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:49.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  6x -0:48.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  6x -0:44.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:42.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:40.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:39.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:35.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -0:34.7.0 core:select-down (atom-text-editor.editor.mini.is-focused)
  6x -0:33.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
 19x -0:32.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:27.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  4x -0:27.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:21.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13 core:undo (atom-text-editor.editor.is-focused)
     -0:05.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "php-class-tree"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-minify, v0.4.2
autocomplete-paths, v1.0.2
cakephp3-snippets, v0.5.0
cdnjs-atom-extension, v1.5.2
color-picker, v2.0.12
emmet, v2.3.13
fetch, v0.3.0
language-ini, v1.12.0
language-powershell, v2.1.0
linter, v1.6.0
linter-clang, v3.2.2
linter-coffeelint, v1.1.0
linter-gcc, v0.3.8
linter-js-standard, v3.2.0
linter-jsonlint, v1.0.1
linter-less, v2.1.0
linter-lua, v1.0.0
linter-php, v1.0.4
linter-pylint, v1.0.1
linter-ruby, v1.1.1
linter-sass-lint, v0.1.5
linter-tidy, v1.0.1
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-selection, v4.3.0
open-recent, v2.3.0
php-composer-completion, v0.3.4
php-debug, v0.1.3
pigments, v0.15.0
symbol-gen, v1.0.0

# Dev
No dev packages
```
